VampPluginSDK: Vamp::HostExt::PluginChannelAdapter Class Reference
Vamp::HostExt::PluginChannelAdapter Class Reference
#include <vamp-sdk/hostext/PluginChannelAdapter.h>
Detailed Description
PluginChannelAdapter is a Vamp plugin adapter that implements a policy for management of plugins that expect a different number of input channels from the number actually available in the source audio data.
A host using PluginChannelAdapter may ignore the getMinChannelCount and getMaxChannelCount reported by the plugin, and still expect the plugin to run.
PluginChannelAdapter implements the following policy:
If the plugin supports the provided number of channels directly, PluginChannelAdapter will just run the plugin as normal.
If the plugin only supports exactly one channel but more than one channel is provided, PluginChannelAdapter will use the mean of the channels. This ensures that the resulting values remain within the same magnitude range as expected for mono data.
If the plugin requires more than one channel but exactly one is provided, the provided channel will be duplicated across all the plugin input channels.
If none of the above apply:
If the plugin requires more channels than are provided, the minimum acceptable number of channels will be produced by adding empty (zero valued) channels to those provided.
If the plugin requires fewer channels than are provided, the maximum acceptable number of channels will be produced by discarding the excess channels.
Hosts requiring a different channel policy from the above will need to implement it themselves, instead of using PluginChannelAdapter.
Note that PluginChannelAdapter does not override the minimum and maximum channel counts returned by the wrapped plugin. The host will need to be aware that it is using a PluginChannelAdapter, and be prepared to ignore these counts as necessary. (This contrasts with the approach used in PluginInputDomainAdapter, which aims to make the host completely unaware of which underlying input domain is in fact in use.)
(The rationale for this is that a host may wish to use the PluginChannelAdapter but still discriminate in some way on the basis of the number of channels actually supported. For example, a simple stereo audio host may prefer to reject plugins that require more than two channels on the grounds that doesn't actually understand what they are for, rather than allow the channel adapter to make a potentially meaningless channel conversion for them.)
In every respect other than its management of channels, the PluginChannelAdapter behaves identically to the plugin that it wraps. The wrapped plugin will be deleted when the wrapper is deleted.
Note:
This class was introduced in version 1.1 of the Vamp plugin SDK.
Definition at line 109 of file PluginChannelAdapter.h.
Public Types
enum InputDomain { TimeDomain, FrequencyDomain }
typedef std::vector
< OutputDescriptor > OutputList
typedef std::vector< Feature > FeatureList
typedef std::map< int,
FeatureList > FeatureSet
typedef std::vector
< ParameterDescriptor > ParameterList
typedef std::vector< std::string > ProgramList
Public Member Functions
PluginChannelAdapter (Plugin *plugin)
virtual ~PluginChannelAdapter ()
bool initialise (size_t channels, size_t stepSize, size_t blockSize)
Initialise a plugin to prepare it for use with the given number of input channels, step size (window increment, in sample frames) and block size (window size, in sample frames).
FeatureSet process (const float *const *inputBuffers, RealTime timestamp)
Process a single block of input data.
void reset ()
Reset the plugin after use, to prepare it for another clean run.
InputDomain getInputDomain () const
Get the plugin's required input domain.
unsigned int getVampApiVersion () const
Get the Vamp API compatibility level of the plugin.
std::string getIdentifier () const
Get the computer-usable name of the plugin.
std::string getName () const
Get a human-readable name or title of the plugin.
std::string getDescription () const
Get a human-readable description for the plugin, typically a line of text that may optionally be displayed in addition to the plugin's "name".
std::string getMaker () const
Get the name of the author or vendor of the plugin in human-readable form.
int getPluginVersion () const
Get the version number of the plugin.
std::string getCopyright () const
Get the copyright statement or licensing summary for the plugin.
ParameterList getParameterDescriptors () const
Get the controllable parameters of this plugin.
float getParameter (std::string) const
Get the value of a named parameter.
void setParameter (std::string, float)
Set a named parameter.
ProgramList getPrograms () const
Get the program settings available in this plugin.
std::string getCurrentProgram () const
Get the current program.
void selectProgram (std::string)
Select a program.
size_t getPreferredStepSize () const
Get the preferred step size (window increment -- the distance in sample frames between the start frames of consecutive blocks passed to the process() function) for the plugin.
size_t getPreferredBlockSize () const
Get the preferred block size (window size -- the number of sample frames passed in each block to the process() function).
size_t getMinChannelCount () const
Get the minimum supported number of input channels.
size_t getMaxChannelCount () const
Get the maximum supported number of input channels.
OutputList getOutputDescriptors () const
Get the outputs of this plugin.
FeatureSet getRemainingFeatures ()
After all blocks have been processed, calculate and return any remaining features derived from the complete input.
virtual std::string getType () const
Used to distinguish between Vamp::Plugin and other potential sibling subclasses of PluginBase.
Protected Attributes
Impl * m_impl
Plugin * m_plugin
float m_inputSampleRate
Classes
class Impl
Member Typedef Documentation
typedef std::vector<OutputDescriptor> Vamp::Plugin::OutputList [inherited]
Definition at line 309 of file Plugin.h.
typedef std::vector<Feature> Vamp::Plugin::FeatureList [inherited]
Definition at line 347 of file Plugin.h.
typedef std::map<int, FeatureList> Vamp::Plugin::FeatureSet [inherited]
Definition at line 348 of file Plugin.h.
typedef std::vector<ParameterDescriptor> Vamp::PluginBase::ParameterList [inherited]
Definition at line 195 of file PluginBase.h.
typedef std::vector<std::string> Vamp::PluginBase::ProgramList [inherited]
Definition at line 217 of file PluginBase.h.
Member Enumeration Documentation
enum Vamp::Plugin::InputDomain [inherited]
Enumerator:
TimeDomain
FrequencyDomain
Definition at line 149 of file Plugin.h.
Constructor & Destructor Documentation
Vamp::HostExt::PluginChannelAdapter::PluginChannelAdapter (Plugin * plugin)
Definition at line 62 of file PluginChannelAdapter.cpp.
References m_impl.
Vamp::HostExt::PluginChannelAdapter::~PluginChannelAdapter () [virtual]
Definition at line 68 of file PluginChannelAdapter.cpp.
References m_impl.
Member Function Documentation
bool Vamp::HostExt::PluginChannelAdapter::initialise (size_t inputChannels, size_t stepSize, size_t blockSize) [virtual]
Initialise a plugin to prepare it for use with the given number of input channels, step size (window increment, in sample frames) and block size (window size, in sample frames).
The input sample rate should have been already specified at construction time.
Return true for successful initialisation, false if the number of input channels, step size and/or block size cannot be supported.
Reimplemented from Vamp::HostExt::PluginWrapper.
Definition at line 74 of file PluginChannelAdapter.cpp.
References Vamp::HostExt::PluginChannelAdapter::Impl::initialise(), and m_impl.
PluginChannelAdapter::FeatureSet Vamp::HostExt::PluginChannelAdapter::process (const float *const * inputBuffers, RealTime timestamp) [virtual]
Process a single block of input data.
If the plugin's inputDomain is TimeDomain, inputBuffers will point to one array of floats per input channel, and each of these arrays will contain blockSize consecutive audio samples (the host will zero-pad as necessary). The timestamp will be the real time in seconds of the start of the supplied block of samples.
If the plugin's inputDomain is FrequencyDomain, inputBuffers will point to one array of floats per input channel, and each of these arrays will contain blockSize/2+1 consecutive pairs of real and imaginary component floats corresponding to bins 0..(blockSize/2) of the FFT output. That is, bin 0 (the first pair of floats) contains the DC output, up to bin blockSize/2 which contains the Nyquist-frequency output. There will therefore be blockSize+2 floats per channel in total. The timestamp will be the real time in seconds of the centre of the FFT input window (i.e. the very first block passed to process might contain the FFT of half a block of zero samples and the first half-block of the actual data, with a timestamp of zero).
Return any features that have become available after this process call. (These do not necessarily have to fall within the process block, except for OneSamplePerStep outputs.)
Reimplemented from Vamp::HostExt::PluginWrapper.
Definition at line 80 of file PluginChannelAdapter.cpp.
References m_impl, and Vamp::HostExt::PluginChannelAdapter::Impl::process().
void Vamp::HostExt::PluginWrapper::reset () [virtual, inherited]
Reset the plugin after use, to prepare it for another clean run.
Not called for the first initialisation (i.e. initialise must also do a reset).
Implements Vamp::Plugin.
Reimplemented in Vamp::HostExt::PluginBufferingAdapter.
Definition at line 68 of file PluginWrapper.cpp.
References Vamp::HostExt::PluginWrapper::m_plugin, and Vamp::Plugin::reset().
Plugin::InputDomain Vamp::HostExt::PluginWrapper::getInputDomain () const [virtual, inherited]
Get the plugin's required input domain.
If this is TimeDomain, the samples provided to the process() function (below) will be in the time domain, as for a traditional audio processing plugin. If this is FrequencyDomain, the host will carry out a windowed FFT of size equal to the negotiated block size on the data before passing the frequency bin data in to process(). The plugin does not get to choose the window type -- the host will either let the user do so, or will use a Hanning window.
Implements Vamp::Plugin.
Reimplemented in Vamp::HostExt::PluginInputDomainAdapter.
Definition at line 74 of file PluginWrapper.cpp.
References Vamp::Plugin::getInputDomain(), and Vamp::HostExt::PluginWrapper::m_plugin.
unsigned int Vamp::HostExt::PluginWrapper::getVampApiVersion () const [virtual, inherited]
Get the Vamp API compatibility level of the plugin.
Reimplemented from Vamp::PluginBase.
Definition at line 80 of file PluginWrapper.cpp.
References Vamp::PluginBase::getVampApiVersion(), and Vamp::HostExt::PluginWrapper::m_plugin.
std::string Vamp::HostExt::PluginWrapper::getIdentifier () const [virtual, inherited]
Get the computer-usable name of the plugin.
This should be reasonably short and contain no whitespace or punctuation characters. It may only contain the characters [a-zA-Z0-9_-]. This is the authoritative way for a program to identify a plugin within a given library.
This text may be visible to the user, but it should not be the main text used to identify a plugin to the user (that will be the name, below).
Example: "zero_crossings"
Implements Vamp::PluginBase.
Definition at line 86 of file PluginWrapper.cpp.
References Vamp::PluginBase::getIdentifier(), and Vamp::HostExt::PluginWrapper::m_plugin.
std::string Vamp::HostExt::PluginWrapper::getName () const [virtual, inherited]
Get a human-readable name or title of the plugin.
This should be brief and self-contained, as it may be used to identify the plugin to the user in isolation (i.e. without also showing the plugin's "identifier").
Example: "Zero Crossings"
Implements Vamp::PluginBase.
Definition at line 92 of file PluginWrapper.cpp.
References Vamp::PluginBase::getName(), and Vamp::HostExt::PluginWrapper::m_plugin.
std::string Vamp::HostExt::PluginWrapper::getDescription () const [virtual, inherited]
Get a human-readable description for the plugin, typically a line of text that may optionally be displayed in addition to the plugin's "name".
May be empty if the name has said it all already.
Example: "Detect and count zero crossing points"
Implements Vamp::PluginBase.
Definition at line 98 of file PluginWrapper.cpp.
References Vamp::PluginBase::getDescription(), and Vamp::HostExt::PluginWrapper::m_plugin.
std::string Vamp::HostExt::PluginWrapper::getMaker () const [virtual, inherited]
Get the name of the author or vendor of the plugin in human-readable form.
This should be a short identifying text, as it may be used to label plugins from the same source in a menu or similar.
Implements Vamp::PluginBase.
Definition at line 104 of file PluginWrapper.cpp.
References Vamp::PluginBase::getMaker(), and Vamp::HostExt::PluginWrapper::m_plugin.
int Vamp::HostExt::PluginWrapper::getPluginVersion () const [virtual, inherited]
Get the version number of the plugin.
Implements Vamp::PluginBase.
Definition at line 110 of file PluginWrapper.cpp.
References Vamp::PluginBase::getPluginVersion(), and Vamp::HostExt::PluginWrapper::m_plugin.
std::string Vamp::HostExt::PluginWrapper::getCopyright () const [virtual, inherited]
Get the copyright statement or licensing summary for the plugin.
This can be an informative text, without the same presentation constraints as mentioned for getMaker above.
Implements Vamp::PluginBase.
Definition at line 116 of file PluginWrapper.cpp.
References Vamp::PluginBase::getCopyright(), and Vamp::HostExt::PluginWrapper::m_plugin.
PluginBase::ParameterList Vamp::HostExt::PluginWrapper::getParameterDescriptors () const [virtual, inherited]
Get the controllable parameters of this plugin.
Reimplemented from Vamp::PluginBase.
Definition at line 122 of file PluginWrapper.cpp.
References Vamp::PluginBase::getParameterDescriptors(), and Vamp::HostExt::PluginWrapper::m_plugin.
float Vamp::HostExt::PluginWrapper::getParameter (std::string) const [virtual, inherited]
Get the value of a named parameter.
The argument is the identifier field from that parameter's descriptor.
Reimplemented from Vamp::PluginBase.
Definition at line 128 of file PluginWrapper.cpp.
References Vamp::PluginBase::getParameter(), and Vamp::HostExt::PluginWrapper::m_plugin.
void Vamp::HostExt::PluginWrapper::setParameter (std::string , float) [virtual, inherited]
Set a named parameter.
The first argument is the identifier field from that parameter's descriptor.
Reimplemented from Vamp::PluginBase.
Definition at line 134 of file PluginWrapper.cpp.
References Vamp::HostExt::PluginWrapper::m_plugin, and Vamp::PluginBase::setParameter().
PluginBase::ProgramList Vamp::HostExt::PluginWrapper::getPrograms () const [virtual, inherited]
Get the program settings available in this plugin.
A program is a named shorthand for a set of parameter values; changing the program may cause the plugin to alter the values of its published parameters (and/or non-public internal processing parameters). The host should re-read the plugin's parameter values after setting a new program.
The programs must have unique names.
Reimplemented from Vamp::PluginBase.
Definition at line 140 of file PluginWrapper.cpp.
References Vamp::PluginBase::getPrograms(), and Vamp::HostExt::PluginWrapper::m_plugin.
std::string Vamp::HostExt::PluginWrapper::getCurrentProgram () const [virtual, inherited]
Get the current program.
Reimplemented from Vamp::PluginBase.
Definition at line 146 of file PluginWrapper.cpp.
References Vamp::PluginBase::getCurrentProgram(), and Vamp::HostExt::PluginWrapper::m_plugin.
void Vamp::HostExt::PluginWrapper::selectProgram (std::string) [virtual, inherited]
Select a program.
(If the given program name is not one of the available programs, do nothing.)
Reimplemented from Vamp::PluginBase.
Definition at line 152 of file PluginWrapper.cpp.
References Vamp::HostExt::PluginWrapper::m_plugin, and Vamp::PluginBase::selectProgram().
size_t Vamp::HostExt::PluginWrapper::getPreferredStepSize () const [virtual, inherited]
Get the preferred step size (window increment -- the distance in sample frames between the start frames of consecutive blocks passed to the process() function) for the plugin.
This should be called before initialise().
A plugin may return 0 if it has no particular interest in the step size. In this case, the host should make the step size equal to the block size if the plugin is accepting input in the time domain. If the plugin is accepting input in the frequency domain, the host may use any step size. The final step size will be set in the initialise() call.
Reimplemented from Vamp::Plugin.
Reimplemented in Vamp::HostExt::PluginBufferingAdapter, and Vamp::HostExt::PluginInputDomainAdapter.
Definition at line 158 of file PluginWrapper.cpp.
References Vamp::Plugin::getPreferredStepSize(), and Vamp::HostExt::PluginWrapper::m_plugin.
size_t Vamp::HostExt::PluginWrapper::getPreferredBlockSize () const [virtual, inherited]
Get the preferred block size (window size -- the number of sample frames passed in each block to the process() function).
This should be called before initialise().
A plugin that can handle any block size may return 0. The final block size will be set in the initialise() call.
Reimplemented from Vamp::Plugin.
Reimplemented in Vamp::HostExt::PluginInputDomainAdapter.
Definition at line 164 of file PluginWrapper.cpp.
References Vamp::Plugin::getPreferredBlockSize(), and Vamp::HostExt::PluginWrapper::m_plugin.
Referenced by Vamp::HostExt::PluginBufferingAdapter::getPreferredStepSize().
size_t Vamp::HostExt::PluginWrapper::getMinChannelCount () const [virtual, inherited]
Get the minimum supported number of input channels.
Reimplemented from Vamp::Plugin.
Definition at line 170 of file PluginWrapper.cpp.
References Vamp::Plugin::getMinChannelCount(), and Vamp::HostExt::PluginWrapper::m_plugin.
size_t Vamp::HostExt::PluginWrapper::getMaxChannelCount () const [virtual, inherited]
Get the maximum supported number of input channels.
Reimplemented from Vamp::Plugin.
Definition at line 175 of file PluginWrapper.cpp.
References Vamp::Plugin::getMaxChannelCount(), and Vamp::HostExt::PluginWrapper::m_plugin.
Plugin::OutputList Vamp::HostExt::PluginWrapper::getOutputDescriptors () const [virtual, inherited]
Get the outputs of this plugin.
An output's index in this list is used as its numeric index when looking it up in the FeatureSet returned from the process() call.
Implements Vamp::Plugin.
Reimplemented in Vamp::HostExt::PluginBufferingAdapter.
Definition at line 181 of file PluginWrapper.cpp.
References Vamp::Plugin::getOutputDescriptors(), and Vamp::HostExt::PluginWrapper::m_plugin.
Plugin::FeatureSet Vamp::HostExt::PluginWrapper::getRemainingFeatures () [virtual, inherited]
After all blocks have been processed, calculate and return any remaining features derived from the complete input.
Implements Vamp::Plugin.
Reimplemented in Vamp::HostExt::PluginBufferingAdapter.
Definition at line 193 of file PluginWrapper.cpp.
References Vamp::Plugin::getRemainingFeatures(), and Vamp::HostExt::PluginWrapper::m_plugin.
virtual std::string Vamp::Plugin::getType () const [inline, virtual, inherited]
Used to distinguish between Vamp::Plugin and other potential sibling subclasses of PluginBase.
Do not reimplement this function in your subclass.
Implements Vamp::PluginBase.
Definition at line 391 of file Plugin.h.
Member Data Documentation
Impl* Vamp::HostExt::PluginChannelAdapter::m_impl [protected]
Definition at line 120 of file PluginChannelAdapter.h.
Referenced by initialise(), PluginChannelAdapter(), process(), and ~PluginChannelAdapter().
Plugin* Vamp::HostExt::PluginWrapper::m_plugin [protected, inherited]
Definition at line 99 of file PluginWrapper.h.
Referenced by Vamp::HostExt::PluginWrapper::getCopyright(), Vamp::HostExt::PluginWrapper::getCurrentProgram(), Vamp::HostExt::PluginWrapper::getDescription(), Vamp::HostExt::PluginWrapper::getIdentifier(), Vamp::HostExt::PluginWrapper::getInputDomain(), Vamp::HostExt::PluginWrapper::getMaker(), Vamp::HostExt::PluginWrapper::getMaxChannelCount(), Vamp::HostExt::PluginWrapper::getMinChannelCount(), Vamp::HostExt::PluginWrapper::getName(), Vamp::HostExt::PluginWrapper::getOutputDescriptors(), Vamp::HostExt::PluginWrapper::getParameter(), Vamp::HostExt::PluginWrapper::getParameterDescriptors(), Vamp::HostExt::PluginWrapper::getPluginVersion(), Vamp::HostExt::PluginWrapper::getPreferredBlockSize(), Vamp::HostExt::PluginWrapper::getPreferredStepSize(), Vamp::HostExt::PluginWrapper::getPrograms(), Vamp::HostExt::PluginWrapper::getRemainingFeatures(), Vamp::HostExt::PluginWrapper::getVampApiVersion(), Vamp::HostExt::PluginWrapper::initialise(), Vamp::HostExt::PluginWrapper::process(), Vamp::HostExt::PluginWrapper::reset(), Vamp::HostExt::PluginWrapper::selectProgram(), Vamp::HostExt::PluginWrapper::setParameter(), Vamp::HostExt::PluginLoader::Impl::PluginDeletionNotifyAdapter::~PluginDeletionNotifyAdapter(), and Vamp::HostExt::PluginWrapper::~PluginWrapper().
float Vamp::Plugin::m_inputSampleRate [protected, inherited]
Definition at line 397 of file Plugin.h.
Referenced by ZeroCrossing::getOutputDescriptors(), PercussionOnsetDetector::getOutputDescriptors(), Vamp::HostExt::PluginRateExtractor::getRate(), AmplitudeFollower::initialise(), Vamp::HostExt::PluginBufferingAdapter::PluginBufferingAdapter(), Vamp::HostExt::PluginInputDomainAdapter::PluginInputDomainAdapter(), ZeroCrossing::process(), SpectralCentroid::process(), and PercussionOnsetDetector::process().
The documentation for this class was generated from the following files:
PluginChannelAdapter.h
PluginChannelAdapter.cpp