VampPluginSDK: Vamp::PluginAdapterBase::Impl Class Reference
Vamp::PluginAdapterBase::Impl Class Reference
Detailed Description
Definition at line 46 of file PluginAdapter.cpp.
Public Member Functions
Impl (PluginAdapterBase *)
~Impl ()
const VampPluginDescriptor * getDescriptor ()
Protected Types
typedef std::map< const void
*, Impl * > AdapterMap
typedef std::map< Plugin
*, Plugin::OutputList * > OutputMap
Protected Member Functions
void cleanup (Plugin *plugin)
void checkOutputMap (Plugin *plugin)
unsigned int getOutputCount (Plugin *plugin)
VampOutputDescriptor * getOutputDescriptor (Plugin *plugin, unsigned int i)
VampFeatureList * process (Plugin *plugin, const float *const *inputBuffers, int sec, int nsec)
VampFeatureList * getRemainingFeatures (Plugin *plugin)
VampFeatureList * convertFeatures (Plugin *plugin, const Plugin::FeatureSet &features)
void resizeFS (Plugin *plugin, int n)
void resizeFL (Plugin *plugin, int n, size_t sz)
void resizeFV (Plugin *plugin, int n, int j, size_t sz)
Static Protected Member Functions
static VampPluginHandle vampInstantiate (const VampPluginDescriptor *desc, float inputSampleRate)
static void vampCleanup (VampPluginHandle handle)
static int vampInitialise (VampPluginHandle handle, unsigned int channels, unsigned int stepSize, unsigned int blockSize)
static void vampReset (VampPluginHandle handle)
static float vampGetParameter (VampPluginHandle handle, int param)
static void vampSetParameter (VampPluginHandle handle, int param, float value)
static unsigned int vampGetCurrentProgram (VampPluginHandle handle)
static void vampSelectProgram (VampPluginHandle handle, unsigned int program)
static unsigned int vampGetPreferredStepSize (VampPluginHandle handle)
static unsigned int vampGetPreferredBlockSize (VampPluginHandle handle)
static unsigned int vampGetMinChannelCount (VampPluginHandle handle)
static unsigned int vampGetMaxChannelCount (VampPluginHandle handle)
static unsigned int vampGetOutputCount (VampPluginHandle handle)
static VampOutputDescriptor * vampGetOutputDescriptor (VampPluginHandle handle, unsigned int i)
static void vampReleaseOutputDescriptor (VampOutputDescriptor *desc)
static VampFeatureList * vampProcess (VampPluginHandle handle, const float *const *inputBuffers, int sec, int nsec)
static VampFeatureList * vampGetRemainingFeatures (VampPluginHandle handle)
static void vampReleaseFeatureSet (VampFeatureList *fs)
static Impl * lookupAdapter (VampPluginHandle)
Protected Attributes
PluginAdapterBase * m_base
bool m_populated
VampPluginDescriptor m_descriptor
Plugin::ParameterList m_parameters
Plugin::ProgramList m_programs
OutputMap m_pluginOutputs
std::map< Plugin
*, VampFeatureList * > m_fs
std::map< Plugin
*, std::vector< size_t > > m_fsizes
std::map< Plugin
*, std::vector< std::vector
< size_t > > > m_fvsizes
Static Protected Attributes
static AdapterMap * m_adapterMap = 0
Member Typedef Documentation
typedef std::map<const void *, Impl *> Vamp::PluginAdapterBase::Impl::AdapterMap [protected]
Definition at line 107 of file PluginAdapter.cpp.
typedef std::map<Plugin *, Plugin::OutputList *> Vamp::PluginAdapterBase::Impl::OutputMap [protected]
Definition at line 116 of file PluginAdapter.cpp.
Constructor & Destructor Documentation
Vamp::PluginAdapterBase::Impl::Impl (PluginAdapterBase * base)
Definition at line 143 of file PluginAdapter.cpp.
Vamp::PluginAdapterBase::Impl::~Impl ()
Definition at line 258 of file PluginAdapter.cpp.
References _VampPluginDescriptor::copyright, _VampParameterDescriptor::description, _VampPluginDescriptor::description, _VampParameterDescriptor::identifier, _VampPluginDescriptor::identifier, m_adapterMap, m_descriptor, m_populated, _VampPluginDescriptor::maker, _VampParameterDescriptor::name, _VampPluginDescriptor::name, _VampPluginDescriptor::parameterCount, _VampPluginDescriptor::parameters, _VampPluginDescriptor::programCount, _VampPluginDescriptor::programs, _VampParameterDescriptor::unit, and _VampParameterDescriptor::valueNames.
Member Function Documentation
const VampPluginDescriptor * Vamp::PluginAdapterBase::Impl::getDescriptor ()
Definition at line 153 of file PluginAdapter.cpp.
References _VampPluginDescriptor::cleanup, _VampPluginDescriptor::copyright, Vamp::PluginAdapterBase::createPlugin(), _VampParameterDescriptor::defaultValue, _VampParameterDescriptor::description, _VampPluginDescriptor::description, Vamp::Plugin::FrequencyDomain, Vamp::PluginBase::getCopyright(), _VampPluginDescriptor::getCurrentProgram, Vamp::PluginBase::getDescription(), Vamp::PluginBase::getIdentifier(), Vamp::Plugin::getInputDomain(), Vamp::PluginBase::getMaker(), _VampPluginDescriptor::getMaxChannelCount, _VampPluginDescriptor::getMinChannelCount, Vamp::PluginBase::getName(), _VampPluginDescriptor::getOutputCount, _VampPluginDescriptor::getOutputDescriptor, _VampPluginDescriptor::getParameter, Vamp::PluginBase::getParameterDescriptors(), Vamp::PluginBase::getPluginVersion(), _VampPluginDescriptor::getPreferredBlockSize, _VampPluginDescriptor::getPreferredStepSize, Vamp::PluginBase::getPrograms(), _VampPluginDescriptor::getRemainingFeatures, Vamp::PluginBase::getVampApiVersion(), _VampParameterDescriptor::identifier, _VampPluginDescriptor::identifier, _VampPluginDescriptor::initialise, _VampPluginDescriptor::inputDomain, _VampPluginDescriptor::instantiate, _VampParameterDescriptor::isQuantized, m_adapterMap, m_base, m_descriptor, m_parameters, m_populated, m_programs, _VampPluginDescriptor::maker, _VampParameterDescriptor::maxValue, _VampParameterDescriptor::minValue, _VampParameterDescriptor::name, _VampPluginDescriptor::name, _VampPluginDescriptor::parameterCount, _VampPluginDescriptor::parameters, _VampPluginDescriptor::pluginVersion, _VampPluginDescriptor::process, _VampPluginDescriptor::programCount, _VampPluginDescriptor::programs, _VampParameterDescriptor::quantizeStep, _VampPluginDescriptor::releaseFeatureSet, _VampPluginDescriptor::releaseOutputDescriptor, _VampPluginDescriptor::reset, _VampPluginDescriptor::selectProgram, _VampPluginDescriptor::setParameter, _VampParameterDescriptor::unit, _VampParameterDescriptor::valueNames, VAMP_API_VERSION, _VampPluginDescriptor::vampApiVersion, vampCleanup(), vampFrequencyDomain, vampGetCurrentProgram(), vampGetMaxChannelCount(), vampGetMinChannelCount(), vampGetOutputCount(), vampGetOutputDescriptor(), vampGetParameter(), vampGetPreferredBlockSize(), vampGetPreferredStepSize(), vampGetRemainingFeatures(), vampInitialise(), vampInstantiate(), vampProcess(), vampReleaseFeatureSet(), vampReleaseOutputDescriptor(), vampReset(), vampSelectProgram(), vampSetParameter(), and vampTimeDomain.
Referenced by Vamp::PluginAdapterBase::getDescriptor().
VampPluginHandle Vamp::PluginAdapterBase::Impl::vampInstantiate (const VampPluginDescriptor * desc, float inputSampleRate) [static, protected]
Definition at line 317 of file PluginAdapter.cpp.
References Vamp::PluginAdapterBase::createPlugin(), m_adapterMap, m_base, and m_descriptor.
Referenced by getDescriptor().
void Vamp::PluginAdapterBase::Impl::vampCleanup (VampPluginHandle handle) [static, protected]
Definition at line 349 of file PluginAdapter.cpp.
References cleanup(), and lookupAdapter().
Referenced by getDescriptor().
int Vamp::PluginAdapterBase::Impl::vampInitialise (VampPluginHandle handle, unsigned int channels, unsigned int stepSize, unsigned int blockSize) [static, protected]
Definition at line 364 of file PluginAdapter.cpp.
Referenced by getDescriptor().
void Vamp::PluginAdapterBase::Impl::vampReset (VampPluginHandle handle) [static, protected]
Definition at line 379 of file PluginAdapter.cpp.
Referenced by getDescriptor().
float Vamp::PluginAdapterBase::Impl::vampGetParameter (VampPluginHandle handle, int param) [static, protected]
Definition at line 389 of file PluginAdapter.cpp.
References lookupAdapter(), and m_parameters.
Referenced by getDescriptor().
void Vamp::PluginAdapterBase::Impl::vampSetParameter (VampPluginHandle handle, int param, float value) [static, protected]
Definition at line 403 of file PluginAdapter.cpp.
References lookupAdapter(), and m_parameters.
Referenced by getDescriptor().
unsigned int Vamp::PluginAdapterBase::Impl::vampGetCurrentProgram (VampPluginHandle handle) [static, protected]
Definition at line 417 of file PluginAdapter.cpp.
References lookupAdapter(), and m_programs.
Referenced by getDescriptor().
void Vamp::PluginAdapterBase::Impl::vampSelectProgram (VampPluginHandle handle, unsigned int program) [static, protected]
Definition at line 434 of file PluginAdapter.cpp.
References lookupAdapter(), and m_programs.
Referenced by getDescriptor().
unsigned int Vamp::PluginAdapterBase::Impl::vampGetPreferredStepSize (VampPluginHandle handle) [static, protected]
Definition at line 448 of file PluginAdapter.cpp.
Referenced by getDescriptor().
unsigned int Vamp::PluginAdapterBase::Impl::vampGetPreferredBlockSize (VampPluginHandle handle) [static, protected]
Definition at line 458 of file PluginAdapter.cpp.
Referenced by getDescriptor().
unsigned int Vamp::PluginAdapterBase::Impl::vampGetMinChannelCount (VampPluginHandle handle) [static, protected]
Definition at line 468 of file PluginAdapter.cpp.
Referenced by getDescriptor().
unsigned int Vamp::PluginAdapterBase::Impl::vampGetMaxChannelCount (VampPluginHandle handle) [static, protected]
Definition at line 478 of file PluginAdapter.cpp.
Referenced by getDescriptor().
unsigned int Vamp::PluginAdapterBase::Impl::vampGetOutputCount (VampPluginHandle handle) [static, protected]
Definition at line 488 of file PluginAdapter.cpp.
References getOutputCount(), and lookupAdapter().
Referenced by getDescriptor().
VampOutputDescriptor * Vamp::PluginAdapterBase::Impl::vampGetOutputDescriptor (VampPluginHandle handle, unsigned int i) [static, protected]
Definition at line 503 of file PluginAdapter.cpp.
References getOutputDescriptor(), and lookupAdapter().
Referenced by getDescriptor().
void Vamp::PluginAdapterBase::Impl::vampReleaseOutputDescriptor (VampOutputDescriptor * desc) [static, protected]
Definition at line 519 of file PluginAdapter.cpp.
References _VampOutputDescriptor::binCount, _VampOutputDescriptor::binNames, _VampOutputDescriptor::description, _VampOutputDescriptor::hasFixedBinCount, _VampOutputDescriptor::identifier, _VampOutputDescriptor::name, and _VampOutputDescriptor::unit.
Referenced by getDescriptor().
VampFeatureList * Vamp::PluginAdapterBase::Impl::vampProcess (VampPluginHandle handle, const float *const * inputBuffers, int sec, int nsec) [static, protected]
Definition at line 541 of file PluginAdapter.cpp.
References lookupAdapter(), and process().
Referenced by getDescriptor().
VampFeatureList * Vamp::PluginAdapterBase::Impl::vampGetRemainingFeatures (VampPluginHandle handle) [static, protected]
Definition at line 557 of file PluginAdapter.cpp.
References getRemainingFeatures(), and lookupAdapter().
Referenced by getDescriptor().
void Vamp::PluginAdapterBase::Impl::vampReleaseFeatureSet (VampFeatureList * fs) [static, protected]
Definition at line 569 of file PluginAdapter.cpp.
Referenced by getDescriptor().
void Vamp::PluginAdapterBase::Impl::cleanup (Plugin * plugin) [protected]
Definition at line 577 of file PluginAdapter.cpp.
References m_adapterMap, m_fs, m_fsizes, m_fvsizes, and m_pluginOutputs.
Referenced by vampCleanup().
void Vamp::PluginAdapterBase::Impl::checkOutputMap (Plugin * plugin) [protected]
Definition at line 619 of file PluginAdapter.cpp.
References Vamp::Plugin::getOutputDescriptors(), and m_pluginOutputs.
Referenced by getOutputCount(), getOutputDescriptor(), getRemainingFeatures(), and process().
unsigned int Vamp::PluginAdapterBase::Impl::getOutputCount (Plugin * plugin) [protected]
Definition at line 630 of file PluginAdapter.cpp.
References checkOutputMap(), and m_pluginOutputs.
Referenced by vampGetOutputCount().
VampOutputDescriptor * Vamp::PluginAdapterBase::Impl::getOutputDescriptor (Plugin * plugin, unsigned int i) [protected]
Definition at line 637 of file PluginAdapter.cpp.
References Vamp::Plugin::OutputDescriptor::binCount, _VampOutputDescriptor::binCount, Vamp::Plugin::OutputDescriptor::binNames, _VampOutputDescriptor::binNames, checkOutputMap(), Vamp::Plugin::OutputDescriptor::description, _VampOutputDescriptor::description, Vamp::Plugin::OutputDescriptor::FixedSampleRate, Vamp::Plugin::OutputDescriptor::hasFixedBinCount, _VampOutputDescriptor::hasFixedBinCount, Vamp::Plugin::OutputDescriptor::hasKnownExtents, _VampOutputDescriptor::hasKnownExtents, Vamp::Plugin::OutputDescriptor::identifier, _VampOutputDescriptor::identifier, Vamp::Plugin::OutputDescriptor::isQuantized, _VampOutputDescriptor::isQuantized, m_pluginOutputs, Vamp::Plugin::OutputDescriptor::maxValue, _VampOutputDescriptor::maxValue, Vamp::Plugin::OutputDescriptor::minValue, _VampOutputDescriptor::minValue, Vamp::Plugin::OutputDescriptor::name, _VampOutputDescriptor::name, Vamp::Plugin::OutputDescriptor::OneSamplePerStep, Vamp::Plugin::OutputDescriptor::quantizeStep, _VampOutputDescriptor::quantizeStep, Vamp::Plugin::OutputDescriptor::sampleRate, _VampOutputDescriptor::sampleRate, _VampOutputDescriptor::sampleType, Vamp::Plugin::OutputDescriptor::sampleType, Vamp::Plugin::OutputDescriptor::unit, _VampOutputDescriptor::unit, vampFixedSampleRate, vampOneSamplePerStep, vampVariableSampleRate, and Vamp::Plugin::OutputDescriptor::VariableSampleRate.
Referenced by vampGetOutputDescriptor().
VampFeatureList * Vamp::PluginAdapterBase::Impl::process (Plugin * plugin, const float *const * inputBuffers, int sec, int nsec) [protected]
Definition at line 690 of file PluginAdapter.cpp.
References checkOutputMap(), convertFeatures(), and Vamp::Plugin::process().
Referenced by vampProcess().
VampFeatureList * Vamp::PluginAdapterBase::Impl::getRemainingFeatures (Plugin * plugin) [protected]
Definition at line 701 of file PluginAdapter.cpp.
References checkOutputMap(), convertFeatures(), and Vamp::Plugin::getRemainingFeatures().
Referenced by vampGetRemainingFeatures().
VampFeatureList * Vamp::PluginAdapterBase::Impl::convertFeatures (Plugin * plugin, const Plugin::FeatureSet & features) [protected]
Definition at line 709 of file PluginAdapter.cpp.
References _VampFeatureList::featureCount, _VampFeatureList::features, _VampFeature::hasTimestamp, _VampFeature::label, m_fs, m_fsizes, m_fvsizes, m_pluginOutputs, _VampFeature::nsec, resizeFL(), resizeFS(), resizeFV(), _VampFeature::sec, _VampFeature::valueCount, and _VampFeature::values.
Referenced by getRemainingFeatures(), and process().
PluginAdapterBase::Impl * Vamp::PluginAdapterBase::Impl::lookupAdapter (VampPluginHandle handle) [static, protected]
Definition at line 304 of file PluginAdapter.cpp.
References m_adapterMap.
Referenced by vampCleanup(), vampGetCurrentProgram(), vampGetOutputCount(), vampGetOutputDescriptor(), vampGetParameter(), vampGetRemainingFeatures(), vampProcess(), vampSelectProgram(), and vampSetParameter().
void Vamp::PluginAdapterBase::Impl::resizeFS (Plugin * plugin, int n) [protected]
Definition at line 788 of file PluginAdapter.cpp.
References m_fs, m_fsizes, and m_fvsizes.
Referenced by convertFeatures().
void Vamp::PluginAdapterBase::Impl::resizeFL (Plugin * plugin, int n, size_t sz) [protected]
Definition at line 810 of file PluginAdapter.cpp.
References m_fs, m_fsizes, and m_fvsizes.
Referenced by convertFeatures().
void Vamp::PluginAdapterBase::Impl::resizeFV (Plugin * plugin, int n, int j, size_t sz) [protected]
Definition at line 833 of file PluginAdapter.cpp.
References m_fs, and m_fvsizes.
Referenced by convertFeatures().
Member Data Documentation
PluginAdapterBase* Vamp::PluginAdapterBase::Impl::m_base [protected]
Definition at line 55 of file PluginAdapter.cpp.
Referenced by getDescriptor(), and vampInstantiate().
PluginAdapterBase::Impl::AdapterMap * Vamp::PluginAdapterBase::Impl::m_adapterMap = 0 [static, protected]
Definition at line 108 of file PluginAdapter.cpp.
Referenced by cleanup(), getDescriptor(), lookupAdapter(), vampInstantiate(), and ~Impl().
bool Vamp::PluginAdapterBase::Impl::m_populated [protected]
Definition at line 111 of file PluginAdapter.cpp.
Referenced by getDescriptor(), and ~Impl().
VampPluginDescriptor Vamp::PluginAdapterBase::Impl::m_descriptor [protected]
Definition at line 112 of file PluginAdapter.cpp.
Referenced by getDescriptor(), vampInstantiate(), and ~Impl().
Plugin::ParameterList Vamp::PluginAdapterBase::Impl::m_parameters [protected]
Definition at line 113 of file PluginAdapter.cpp.
Referenced by getDescriptor(), vampGetParameter(), and vampSetParameter().
Plugin::ProgramList Vamp::PluginAdapterBase::Impl::m_programs [protected]
Definition at line 114 of file PluginAdapter.cpp.
Referenced by getDescriptor(), vampGetCurrentProgram(), and vampSelectProgram().
OutputMap Vamp::PluginAdapterBase::Impl::m_pluginOutputs [protected]
Definition at line 117 of file PluginAdapter.cpp.
Referenced by checkOutputMap(), cleanup(), convertFeatures(), getOutputCount(), and getOutputDescriptor().
std::map<Plugin *, VampFeatureList *> Vamp::PluginAdapterBase::Impl::m_fs [protected]
Definition at line 119 of file PluginAdapter.cpp.
Referenced by cleanup(), convertFeatures(), resizeFL(), resizeFS(), and resizeFV().
std::map<Plugin *, std::vector<size_t> > Vamp::PluginAdapterBase::Impl::m_fsizes [protected]
Definition at line 120 of file PluginAdapter.cpp.
Referenced by cleanup(), convertFeatures(), resizeFL(), and resizeFS().
std::map<Plugin *, std::vector<std::vector<size_t> > > Vamp::PluginAdapterBase::Impl::m_fvsizes [protected]
Definition at line 121 of file PluginAdapter.cpp.
Referenced by cleanup(), convertFeatures(), resizeFL(), resizeFS(), and resizeFV().
The documentation for this class was generated from the following file:
PluginAdapter.cpp