VampPluginSDK: Vamp::HostExt::PluginRateExtractor Class Reference
Vamp::HostExt::PluginRateExtractor Class Reference
Detailed Description
Definition at line 43 of file PluginWrapper.cpp.
Public Types
enum InputDomain { TimeDomain, FrequencyDomain }
typedef std::vector
< OutputDescriptor > OutputList
typedef std::vector< Feature > FeatureList
typedef std::map< int,
FeatureList > FeatureSet
typedef std::vector
< ParameterDescriptor > ParameterList
typedef std::vector< std::string > ProgramList
Public Member Functions
PluginRateExtractor ()
float getRate () const
virtual bool initialise (size_t inputChannels, size_t stepSize, size_t blockSize)=0
Initialise a plugin to prepare it for use with the given number of input channels, step size (window increment, in sample frames) and block size (window size, in sample frames).
virtual void reset ()=0
Reset the plugin after use, to prepare it for another clean run.
virtual InputDomain getInputDomain () const =0
Get the plugin's required input domain.
virtual size_t getPreferredBlockSize () const
Get the preferred block size (window size -- the number of sample frames passed in each block to the process() function).
virtual size_t getPreferredStepSize () const
Get the preferred step size (window increment -- the distance in sample frames between the start frames of consecutive blocks passed to the process() function) for the plugin.
virtual size_t getMinChannelCount () const
Get the minimum supported number of input channels.
virtual size_t getMaxChannelCount () const
Get the maximum supported number of input channels.
virtual OutputList getOutputDescriptors () const =0
Get the outputs of this plugin.
virtual FeatureSet process (const float *const *inputBuffers, RealTime timestamp)=0
Process a single block of input data.
virtual FeatureSet getRemainingFeatures ()=0
After all blocks have been processed, calculate and return any remaining features derived from the complete input.
virtual std::string getType () const
Used to distinguish between Vamp::Plugin and other potential sibling subclasses of PluginBase.
virtual unsigned int getVampApiVersion () const
Get the Vamp API compatibility level of the plugin.
virtual std::string getIdentifier () const =0
Get the computer-usable name of the plugin.
virtual std::string getName () const =0
Get a human-readable name or title of the plugin.
virtual std::string getDescription () const =0
Get a human-readable description for the plugin, typically a line of text that may optionally be displayed in addition to the plugin's "name".
virtual std::string getMaker () const =0
Get the name of the author or vendor of the plugin in human-readable form.
virtual std::string getCopyright () const =0
Get the copyright statement or licensing summary for the plugin.
virtual int getPluginVersion () const =0
Get the version number of the plugin.
virtual ParameterList getParameterDescriptors () const
Get the controllable parameters of this plugin.
virtual float getParameter (std::string) const
Get the value of a named parameter.
virtual void setParameter (std::string, float)
Set a named parameter.
virtual ProgramList getPrograms () const
Get the program settings available in this plugin.
virtual std::string getCurrentProgram () const
Get the current program.
virtual void selectProgram (std::string)
Select a program.
Protected Attributes
float m_inputSampleRate
Member Typedef Documentation
typedef std::vector<OutputDescriptor> Vamp::Plugin::OutputList [inherited]
Definition at line 309 of file Plugin.h.
typedef std::vector<Feature> Vamp::Plugin::FeatureList [inherited]
Definition at line 347 of file Plugin.h.
typedef std::map<int, FeatureList> Vamp::Plugin::FeatureSet [inherited]
Definition at line 348 of file Plugin.h.
typedef std::vector<ParameterDescriptor> Vamp::PluginBase::ParameterList [inherited]
Definition at line 195 of file PluginBase.h.
typedef std::vector<std::string> Vamp::PluginBase::ProgramList [inherited]
Definition at line 217 of file PluginBase.h.
Member Enumeration Documentation
enum Vamp::Plugin::InputDomain [inherited]
Enumerator:
TimeDomain
FrequencyDomain
Definition at line 149 of file Plugin.h.
Constructor & Destructor Documentation
Vamp::HostExt::PluginRateExtractor::PluginRateExtractor () [inline]
Definition at line 46 of file PluginWrapper.cpp.
Member Function Documentation
float Vamp::HostExt::PluginRateExtractor::getRate () const [inline]
Definition at line 47 of file PluginWrapper.cpp.
References Vamp::Plugin::m_inputSampleRate.
virtual bool Vamp::Plugin::initialise (size_t inputChannels, size_t stepSize, size_t blockSize) [pure virtual, inherited]
Initialise a plugin to prepare it for use with the given number of input channels, step size (window increment, in sample frames) and block size (window size, in sample frames).
The input sample rate should have been already specified at construction time.
Return true for successful initialisation, false if the number of input channels, step size and/or block size cannot be supported.
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginBufferingAdapter, Vamp::HostExt::PluginChannelAdapter, Vamp::HostExt::PluginInputDomainAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::HostExt::PluginWrapper::initialise(), Vamp::HostExt::PluginInputDomainAdapter::Impl::initialise(), Vamp::HostExt::PluginChannelAdapter::Impl::initialise(), Vamp::HostExt::PluginBufferingAdapter::Impl::initialise(), and runPlugin().
virtual void Vamp::Plugin::reset () [pure virtual, inherited]
Reset the plugin after use, to prepare it for another clean run.
Not called for the first initialisation (i.e. initialise must also do a reset).
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginBufferingAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::HostExt::PluginWrapper::reset().
virtual InputDomain Vamp::Plugin::getInputDomain () const [pure virtual, inherited]
Get the plugin's required input domain.
If this is TimeDomain, the samples provided to the process() function (below) will be in the time domain, as for a traditional audio processing plugin. If this is FrequencyDomain, the host will carry out a windowed FFT of size equal to the negotiated block size on the data before passing the frequency bin data in to process(). The plugin does not get to choose the window type -- the host will either let the user do so, or will use a Hanning window.
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginInputDomainAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::PluginAdapterBase::Impl::getDescriptor(), Vamp::HostExt::PluginWrapper::getInputDomain(), Vamp::HostExt::PluginInputDomainAdapter::Impl::getPreferredBlockSize(), Vamp::HostExt::PluginInputDomainAdapter::Impl::getPreferredStepSize(), Vamp::HostExt::PluginInputDomainAdapter::Impl::initialise(), Vamp::HostExt::PluginBufferingAdapter::Impl::initialise(), Vamp::HostExt::PluginLoader::Impl::loadPlugin(), Vamp::HostExt::PluginInputDomainAdapter::Impl::process(), and runPlugin().
virtual size_t Vamp::Plugin::getPreferredBlockSize () const [inline, virtual, inherited]
Get the preferred block size (window size -- the number of sample frames passed in each block to the process() function).
This should be called before initialise().
A plugin that can handle any block size may return 0. The final block size will be set in the initialise() call.
Reimplemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginInputDomainAdapter, Vamp::HostExt::PluginWrapper, and PercussionOnsetDetector.
Definition at line 171 of file Plugin.h.
Referenced by Vamp::HostExt::PluginWrapper::getPreferredBlockSize(), Vamp::HostExt::PluginInputDomainAdapter::Impl::getPreferredBlockSize(), Vamp::HostExt::PluginBufferingAdapter::Impl::initialise(), and runPlugin().
virtual size_t Vamp::Plugin::getPreferredStepSize () const [inline, virtual, inherited]
Get the preferred step size (window increment -- the distance in sample frames between the start frames of consecutive blocks passed to the process() function) for the plugin.
This should be called before initialise().
A plugin may return 0 if it has no particular interest in the step size. In this case, the host should make the step size equal to the block size if the plugin is accepting input in the time domain. If the plugin is accepting input in the frequency domain, the host may use any step size. The final step size will be set in the initialise() call.
Reimplemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginBufferingAdapter, Vamp::HostExt::PluginInputDomainAdapter, Vamp::HostExt::PluginWrapper, and PercussionOnsetDetector.
Definition at line 186 of file Plugin.h.
Referenced by Vamp::HostExt::PluginWrapper::getPreferredStepSize(), Vamp::HostExt::PluginInputDomainAdapter::Impl::getPreferredStepSize(), Vamp::HostExt::PluginBufferingAdapter::Impl::initialise(), and runPlugin().
virtual size_t Vamp::Plugin::getMinChannelCount () const [inline, virtual, inherited]
Get the minimum supported number of input channels.
Reimplemented in Vamp::PluginHostAdapter, and Vamp::HostExt::PluginWrapper.
Definition at line 191 of file Plugin.h.
Referenced by Vamp::HostExt::PluginWrapper::getMinChannelCount(), ZeroCrossing::initialise(), SpectralCentroid::initialise(), Vamp::HostExt::PluginChannelAdapter::Impl::initialise(), PercussionOnsetDetector::initialise(), AmplitudeFollower::initialise(), and runPlugin().
virtual size_t Vamp::Plugin::getMaxChannelCount () const [inline, virtual, inherited]
Get the maximum supported number of input channels.
Reimplemented in Vamp::PluginHostAdapter, and Vamp::HostExt::PluginWrapper.
Definition at line 196 of file Plugin.h.
Referenced by Vamp::HostExt::PluginWrapper::getMaxChannelCount(), ZeroCrossing::initialise(), SpectralCentroid::initialise(), Vamp::HostExt::PluginChannelAdapter::Impl::initialise(), PercussionOnsetDetector::initialise(), AmplitudeFollower::initialise(), and runPlugin().
virtual OutputList Vamp::Plugin::getOutputDescriptors () const [pure virtual, inherited]
Get the outputs of this plugin.
An output's index in this list is used as its numeric index when looking it up in the FeatureSet returned from the process() call.
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginBufferingAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::PluginAdapterBase::Impl::checkOutputMap(), enumeratePlugins(), Vamp::HostExt::PluginWrapper::getOutputDescriptors(), Vamp::HostExt::PluginBufferingAdapter::Impl::getOutputDescriptors(), and runPlugin().
virtual FeatureSet Vamp::Plugin::process (const float *const * inputBuffers, RealTime timestamp) [pure virtual, inherited]
Process a single block of input data.
If the plugin's inputDomain is TimeDomain, inputBuffers will point to one array of floats per input channel, and each of these arrays will contain blockSize consecutive audio samples (the host will zero-pad as necessary). The timestamp will be the real time in seconds of the start of the supplied block of samples.
If the plugin's inputDomain is FrequencyDomain, inputBuffers will point to one array of floats per input channel, and each of these arrays will contain blockSize/2+1 consecutive pairs of real and imaginary component floats corresponding to bins 0..(blockSize/2) of the FFT output. That is, bin 0 (the first pair of floats) contains the DC output, up to bin blockSize/2 which contains the Nyquist-frequency output. There will therefore be blockSize+2 floats per channel in total. The timestamp will be the real time in seconds of the centre of the FFT input window (i.e. the very first block passed to process might contain the FFT of half a block of zero samples and the first half-block of the actual data, with a timestamp of zero).
Return any features that have become available after this process call. (These do not necessarily have to fall within the process block, except for OneSamplePerStep outputs.)
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginBufferingAdapter, Vamp::HostExt::PluginChannelAdapter, Vamp::HostExt::PluginInputDomainAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::HostExt::PluginWrapper::process(), Vamp::HostExt::PluginInputDomainAdapter::Impl::process(), Vamp::HostExt::PluginChannelAdapter::Impl::process(), Vamp::PluginAdapterBase::Impl::process(), Vamp::HostExt::PluginBufferingAdapter::Impl::processBlock(), and runPlugin().
virtual FeatureSet Vamp::Plugin::getRemainingFeatures () [pure virtual, inherited]
After all blocks have been processed, calculate and return any remaining features derived from the complete input.
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginBufferingAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::HostExt::PluginWrapper::getRemainingFeatures(), Vamp::HostExt::PluginBufferingAdapter::Impl::getRemainingFeatures(), Vamp::PluginAdapterBase::Impl::getRemainingFeatures(), and runPlugin().
virtual std::string Vamp::Plugin::getType () const [inline, virtual, inherited]
Used to distinguish between Vamp::Plugin and other potential sibling subclasses of PluginBase.
Do not reimplement this function in your subclass.
Implements Vamp::PluginBase.
Definition at line 391 of file Plugin.h.
virtual unsigned int Vamp::PluginBase::getVampApiVersion () const [inline, virtual, inherited]
Get the Vamp API compatibility level of the plugin.
Reimplemented in Vamp::PluginHostAdapter, and Vamp::HostExt::PluginWrapper.
Definition at line 67 of file PluginBase.h.
Referenced by enumeratePlugins(), Vamp::PluginAdapterBase::Impl::getDescriptor(), and Vamp::HostExt::PluginWrapper::getVampApiVersion().
virtual std::string Vamp::PluginBase::getIdentifier () const [pure virtual, inherited]
Get the computer-usable name of the plugin.
This should be reasonably short and contain no whitespace or punctuation characters. It may only contain the characters [a-zA-Z0-9_-]. This is the authoritative way for a program to identify a plugin within a given library.
This text may be visible to the user, but it should not be the main text used to identify a plugin to the user (that will be the name, below).
Example: "zero_crossings"
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by enumeratePlugins(), Vamp::PluginAdapterBase::Impl::getDescriptor(), Vamp::HostExt::PluginWrapper::getIdentifier(), and runPlugin().
virtual std::string Vamp::PluginBase::getName () const [pure virtual, inherited]
Get a human-readable name or title of the plugin.
This should be brief and self-contained, as it may be used to identify the plugin to the user in isolation (i.e. without also showing the plugin's "identifier").
Example: "Zero Crossings"
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by enumeratePlugins(), Vamp::PluginAdapterBase::Impl::getDescriptor(), Vamp::HostExt::PluginWrapper::getName(), and printPluginCategoryList().
virtual std::string Vamp::PluginBase::getDescription () const [pure virtual, inherited]
Get a human-readable description for the plugin, typically a line of text that may optionally be displayed in addition to the plugin's "name".
May be empty if the name has said it all already.
Example: "Detect and count zero crossing points"
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by enumeratePlugins(), Vamp::HostExt::PluginWrapper::getDescription(), Vamp::PluginAdapterBase::Impl::getDescriptor(), and printPluginCategoryList().
virtual std::string Vamp::PluginBase::getMaker () const [pure virtual, inherited]
Get the name of the author or vendor of the plugin in human-readable form.
This should be a short identifying text, as it may be used to label plugins from the same source in a menu or similar.
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by enumeratePlugins(), Vamp::PluginAdapterBase::Impl::getDescriptor(), Vamp::HostExt::PluginWrapper::getMaker(), and printPluginCategoryList().
virtual std::string Vamp::PluginBase::getCopyright () const [pure virtual, inherited]
Get the copyright statement or licensing summary for the plugin.
This can be an informative text, without the same presentation constraints as mentioned for getMaker above.
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::HostExt::PluginWrapper::getCopyright(), and Vamp::PluginAdapterBase::Impl::getDescriptor().
virtual int Vamp::PluginBase::getPluginVersion () const [pure virtual, inherited]
Get the version number of the plugin.
Implemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, PercussionOnsetDetector, SpectralCentroid, and ZeroCrossing.
Referenced by Vamp::PluginAdapterBase::Impl::getDescriptor(), and Vamp::HostExt::PluginWrapper::getPluginVersion().
virtual ParameterList Vamp::PluginBase::getParameterDescriptors () const [inline, virtual, inherited]
Get the controllable parameters of this plugin.
Reimplemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, and PercussionOnsetDetector.
Definition at line 200 of file PluginBase.h.
Referenced by Vamp::PluginAdapterBase::Impl::getDescriptor(), and Vamp::HostExt::PluginWrapper::getParameterDescriptors().
virtual float Vamp::PluginBase::getParameter (std::string) const [inline, virtual, inherited]
Get the value of a named parameter.
The argument is the identifier field from that parameter's descriptor.
Reimplemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, and PercussionOnsetDetector.
Definition at line 208 of file PluginBase.h.
Referenced by Vamp::HostExt::PluginWrapper::getParameter().
virtual void Vamp::PluginBase::setParameter (std::string , float) [inline, virtual, inherited]
Set a named parameter.
The first argument is the identifier field from that parameter's descriptor.
Reimplemented in Vamp::PluginHostAdapter, Vamp::HostExt::PluginWrapper, AmplitudeFollower, and PercussionOnsetDetector.
Definition at line 214 of file PluginBase.h.
Referenced by Vamp::HostExt::PluginWrapper::setParameter().
virtual ProgramList Vamp::PluginBase::getPrograms () const [inline, virtual, inherited]
Get the program settings available in this plugin.
A program is a named shorthand for a set of parameter values; changing the program may cause the plugin to alter the values of its published parameters (and/or non-public internal processing parameters). The host should re-read the plugin's parameter values after setting a new program.
The programs must have unique names.
Reimplemented in Vamp::PluginHostAdapter, and Vamp::HostExt::PluginWrapper.
Definition at line 229 of file PluginBase.h.
Referenced by Vamp::PluginAdapterBase::Impl::getDescriptor(), and Vamp::HostExt::PluginWrapper::getPrograms().
virtual std::string Vamp::PluginBase::getCurrentProgram () const [inline, virtual, inherited]
Get the current program.
Reimplemented in Vamp::PluginHostAdapter, and Vamp::HostExt::PluginWrapper.
Definition at line 234 of file PluginBase.h.
Referenced by Vamp::HostExt::PluginWrapper::getCurrentProgram().
virtual void Vamp::PluginBase::selectProgram (std::string) [inline, virtual, inherited]
Select a program.
(If the given program name is not one of the available programs, do nothing.)
Reimplemented in Vamp::PluginHostAdapter, and Vamp::HostExt::PluginWrapper.
Definition at line 240 of file PluginBase.h.
Referenced by Vamp::HostExt::PluginWrapper::selectProgram().
Member Data Documentation
float Vamp::Plugin::m_inputSampleRate [protected, inherited]
Definition at line 397 of file Plugin.h.
Referenced by ZeroCrossing::getOutputDescriptors(), PercussionOnsetDetector::getOutputDescriptors(), getRate(), AmplitudeFollower::initialise(), Vamp::HostExt::PluginBufferingAdapter::PluginBufferingAdapter(), Vamp::HostExt::PluginInputDomainAdapter::PluginInputDomainAdapter(), ZeroCrossing::process(), SpectralCentroid::process(), and PercussionOnsetDetector::process().
The documentation for this class was generated from the following file:
PluginWrapper.cpp