VampPluginSDK: Vamp::HostExt::PluginInputDomainAdapter::Impl Class Reference
Vamp::HostExt::PluginInputDomainAdapter::Impl Class Reference
Detailed Description
Definition at line 77 of file PluginInputDomainAdapter.cpp.
Public Member Functions
Impl (Plugin *plugin, float inputSampleRate)
~Impl ()
bool initialise (size_t channels, size_t stepSize, size_t blockSize)
size_t getPreferredStepSize () const
size_t getPreferredBlockSize () const
FeatureSet process (const float *const *inputBuffers, RealTime timestamp)
Protected Member Functions
void fft (unsigned int n, bool inverse, double *ri, double *ii, double *ro, double *io)
size_t makeBlockSizeAcceptable (size_t) const
Protected Attributes
Plugin * m_plugin
float m_inputSampleRate
int m_channels
int m_blockSize
float ** m_freqbuf
double * m_ri
double * m_window
double * m_ro
double * m_io
Constructor & Destructor Documentation
Vamp::HostExt::PluginInputDomainAdapter::Impl::Impl (Plugin * plugin, float inputSampleRate)
Definition at line 154 of file PluginInputDomainAdapter.cpp.
Vamp::HostExt::PluginInputDomainAdapter::Impl::~Impl ()
Definition at line 172 of file PluginInputDomainAdapter.cpp.
References m_channels, m_freqbuf, m_io, m_ri, m_ro, and m_window.
Member Function Documentation
bool Vamp::HostExt::PluginInputDomainAdapter::Impl::initialise (size_t channels, size_t stepSize, size_t blockSize)
Definition at line 203 of file PluginInputDomainAdapter.cpp.
References Vamp::Plugin::getInputDomain(), Vamp::Plugin::initialise(), m_blockSize, m_channels, m_freqbuf, m_io, M_PI, m_plugin, m_ri, m_ro, m_window, and Vamp::Plugin::TimeDomain.
Referenced by Vamp::HostExt::PluginInputDomainAdapter::initialise().
size_t Vamp::HostExt::PluginInputDomainAdapter::Impl::getPreferredStepSize () const
Definition at line 271 of file PluginInputDomainAdapter.cpp.
References Vamp::Plugin::FrequencyDomain, Vamp::Plugin::getInputDomain(), getPreferredBlockSize(), Vamp::Plugin::getPreferredStepSize(), and m_plugin.
Referenced by Vamp::HostExt::PluginInputDomainAdapter::getPreferredStepSize().
size_t Vamp::HostExt::PluginInputDomainAdapter::Impl::getPreferredBlockSize () const
Definition at line 283 of file PluginInputDomainAdapter.cpp.
References Vamp::Plugin::FrequencyDomain, Vamp::Plugin::getInputDomain(), Vamp::Plugin::getPreferredBlockSize(), m_plugin, and makeBlockSizeAcceptable().
Referenced by Vamp::HostExt::PluginInputDomainAdapter::getPreferredBlockSize(), and getPreferredStepSize().
Plugin::FeatureSet Vamp::HostExt::PluginInputDomainAdapter::Impl::process (const float *const * inputBuffers, RealTime timestamp)
Definition at line 342 of file PluginInputDomainAdapter.cpp.
References fft(), Vamp::RealTime::frame2RealTime(), Vamp::Plugin::getInputDomain(), m_blockSize, m_channels, m_freqbuf, m_inputSampleRate, m_io, m_plugin, m_ri, m_ro, m_window, Vamp::Plugin::process(), and Vamp::Plugin::TimeDomain.
Referenced by Vamp::HostExt::PluginInputDomainAdapter::process().
void Vamp::HostExt::PluginInputDomainAdapter::Impl::fft (unsigned int n, bool inverse, double * ri, double * ii, double * ro, double * io) [protected]
Definition at line 438 of file PluginInputDomainAdapter.cpp.
References M_PI.
Referenced by process().
size_t Vamp::HostExt::PluginInputDomainAdapter::Impl::makeBlockSizeAcceptable (size_t blockSize) const [protected]
Definition at line 299 of file PluginInputDomainAdapter.cpp.
Referenced by getPreferredBlockSize().
Member Data Documentation
Plugin* Vamp::HostExt::PluginInputDomainAdapter::Impl::m_plugin [protected]
Definition at line 91 of file PluginInputDomainAdapter.cpp.
Referenced by getPreferredBlockSize(), getPreferredStepSize(), initialise(), and process().
float Vamp::HostExt::PluginInputDomainAdapter::Impl::m_inputSampleRate [protected]
Definition at line 92 of file PluginInputDomainAdapter.cpp.
Referenced by process().
int Vamp::HostExt::PluginInputDomainAdapter::Impl::m_channels [protected]
Definition at line 93 of file PluginInputDomainAdapter.cpp.
Referenced by initialise(), process(), and ~Impl().
int Vamp::HostExt::PluginInputDomainAdapter::Impl::m_blockSize [protected]
Definition at line 94 of file PluginInputDomainAdapter.cpp.
Referenced by initialise(), and process().
float** Vamp::HostExt::PluginInputDomainAdapter::Impl::m_freqbuf [protected]
Definition at line 95 of file PluginInputDomainAdapter.cpp.
Referenced by initialise(), process(), and ~Impl().
double* Vamp::HostExt::PluginInputDomainAdapter::Impl::m_ri [protected]
Definition at line 97 of file PluginInputDomainAdapter.cpp.
Referenced by initialise(), process(), and ~Impl().
double* Vamp::HostExt::PluginInputDomainAdapter::Impl::m_window [protected]
Definition at line 98 of file PluginInputDomainAdapter.cpp.
Referenced by initialise(), process(), and ~Impl().
double* Vamp::HostExt::PluginInputDomainAdapter::Impl::m_ro [protected]
Definition at line 104 of file PluginInputDomainAdapter.cpp.
Referenced by initialise(), process(), and ~Impl().
double* Vamp::HostExt::PluginInputDomainAdapter::Impl::m_io [protected]
Definition at line 105 of file PluginInputDomainAdapter.cpp.
Referenced by initialise(), process(), and ~Impl().
The documentation for this class was generated from the following file:
PluginInputDomainAdapter.cpp