VampPluginSDK: Vamp::RealTime Class Reference
Vamp::RealTime Class Reference
#include <vamp-sdk/RealTime.h>
Detailed Description
RealTime represents time values to nanosecond precision with accurate arithmetic and frame-rate conversion functions.
Definition at line 63 of file RealTime.h.
Public Member Functions
int usec () const
int msec () const
RealTime ()
RealTime (int s, int n)
RealTime (const RealTime &r)
RealTime & operator= (const RealTime &r)
RealTime operator+ (const RealTime &r) const
RealTime operator- (const RealTime &r) const
RealTime operator- () const
bool operator< (const RealTime &r) const
bool operator> (const RealTime &r) const
bool operator== (const RealTime &r) const
bool operator!= (const RealTime &r) const
bool operator>= (const RealTime &r) const
bool operator<= (const RealTime &r) const
RealTime operator/ (int d) const
double operator/ (const RealTime &r) const
Return the ratio of two times.
std::string toString () const
Return a human-readable debug-type string to full precision (probably not a format to show to a user directly).
std::string toText (bool fixedDp=false) const
Return a user-readable string to the nearest millisecond in a form like HH:MM:SS.mmm.
Static Public Member Functions
static RealTime fromSeconds (double sec)
static RealTime fromMilliseconds (int msec)
static RealTime fromTimeval (const struct timeval &)
static long realTime2Frame (const RealTime &r, unsigned int sampleRate)
Convert a RealTime into a sample frame at the given sample rate.
static RealTime frame2RealTime (long frame, unsigned int sampleRate)
Convert a sample frame at the given sample rate into a RealTime.
Public Attributes
int sec
int nsec
Static Public Attributes
static const RealTime zeroTime
Constructor & Destructor Documentation
Vamp::RealTime::RealTime () [inline]
Definition at line 71 of file RealTime.h.
Referenced by fromMilliseconds(), fromSeconds(), fromTimeval(), operator+(), operator-(), and operator/().
Vamp::RealTime::RealTime (int s, int n)
Definition at line 75 of file RealTime.cpp.
References nsec, ONE_BILLION, and sec.
Vamp::RealTime::RealTime (const RealTime & r) [inline]
Definition at line 74 of file RealTime.h.
Member Function Documentation
int Vamp::RealTime::usec () const [inline]
Definition at line 68 of file RealTime.h.
References nsec.
int Vamp::RealTime::msec () const [inline]
Definition at line 69 of file RealTime.h.
References nsec.
Referenced by toText().
RealTime Vamp::RealTime::fromSeconds (double sec) [static]
Definition at line 91 of file RealTime.cpp.
References ONE_BILLION, and RealTime().
RealTime Vamp::RealTime::fromMilliseconds (int msec) [static]
Definition at line 97 of file RealTime.cpp.
References RealTime().
RealTime Vamp::RealTime::fromTimeval (const struct timeval & tv) [static]
Definition at line 104 of file RealTime.cpp.
References RealTime().
RealTime& Vamp::RealTime::operator= (const RealTime & r) [inline]
Definition at line 84 of file RealTime.h.
References nsec, and sec.
RealTime Vamp::RealTime::operator+ (const RealTime & r) const [inline]
Definition at line 88 of file RealTime.h.
References nsec, RealTime(), and sec.
RealTime Vamp::RealTime::operator- (const RealTime & r) const [inline]
Definition at line 91 of file RealTime.h.
References nsec, RealTime(), and sec.
RealTime Vamp::RealTime::operator- () const [inline]
Definition at line 94 of file RealTime.h.
References nsec, RealTime(), and sec.
bool Vamp::RealTime::operator< (const RealTime & r) const [inline]
Definition at line 98 of file RealTime.h.
References nsec, and sec.
bool Vamp::RealTime::operator> (const RealTime & r) const [inline]
Definition at line 103 of file RealTime.h.
References nsec, and sec.
bool Vamp::RealTime::operator== (const RealTime & r) const [inline]
Definition at line 108 of file RealTime.h.
References nsec, and sec.
bool Vamp::RealTime::operator!= (const RealTime & r) const [inline]
Definition at line 112 of file RealTime.h.
bool Vamp::RealTime::operator>= (const RealTime & r) const [inline]
Definition at line 116 of file RealTime.h.
References nsec, and sec.
bool Vamp::RealTime::operator<= (const RealTime & r) const [inline]
Definition at line 121 of file RealTime.h.
References nsec, and sec.
RealTime Vamp::RealTime::operator/ (int d) const
Definition at line 203 of file RealTime.cpp.
References nsec, ONE_BILLION, RealTime(), and sec.
double Vamp::RealTime::operator/ (const RealTime & r) const
Return the ratio of two times.
Definition at line 214 of file RealTime.cpp.
References nsec, ONE_BILLION, and sec.
std::string Vamp::RealTime::toString () const
Return a human-readable debug-type string to full precision (probably not a format to show to a user directly).
Definition at line 135 of file RealTime.cpp.
References stringstream.
Referenced by printFeatures().
std::string Vamp::RealTime::toText (bool fixedDp = false) const
Return a user-readable string to the nearest millisecond in a form like HH:MM:SS.mmm.
Definition at line 151 of file RealTime.cpp.
References msec(), sec, stringstream, and zeroTime.
long Vamp::RealTime::realTime2Frame (const RealTime & r, unsigned int sampleRate) [static]
Convert a RealTime into a sample frame at the given sample rate.
Definition at line 224 of file RealTime.cpp.
References nsec, sec, and zeroTime.
Referenced by Vamp::HostExt::PluginBufferingAdapter::Impl::process().
RealTime Vamp::RealTime::frame2RealTime (long frame, unsigned int sampleRate) [static]
Convert a sample frame at the given sample rate into a RealTime.
Definition at line 232 of file RealTime.cpp.
References nsec, and sec.
Referenced by ZeroCrossing::process(), Vamp::HostExt::PluginInputDomainAdapter::Impl::process(), PercussionOnsetDetector::process(), and Vamp::HostExt::PluginBufferingAdapter::Impl::processBlock().
Member Data Documentation
int Vamp::RealTime::sec
Definition at line 65 of file RealTime.h.
Referenced by frame2RealTime(), operator+(), operator-(), operator/(), operator<(), Vamp::operator<<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), Vamp::PluginHostAdapter::process(), RealTime(), realTime2Frame(), and toText().
int Vamp::RealTime::nsec
Definition at line 66 of file RealTime.h.
Referenced by frame2RealTime(), msec(), operator+(), operator-(), operator/(), operator<(), Vamp::operator<<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), Vamp::PluginHostAdapter::process(), RealTime(), realTime2Frame(), and usec().
const RealTime Vamp::RealTime::zeroTime [static]
Definition at line 155 of file RealTime.h.
Referenced by Vamp::operator<<(), realTime2Frame(), and toText().
The documentation for this class was generated from the following files:
RealTime.h
RealTime.cpp